Multiple files

SOURCE:
file: foo.ya
enum Foo {
    X(Bar),
}

file: bar.ya
enum Bar {
    A(int),
}

fn with_foo(f: Foo, m: int) -> int {
    match f {
        Foo.X(b) => match b {
            Bar.A(n) => n + m
        }
    }
}

file: main.ya
fn main() {
    let bar = Bar.A(2)
    assertEq(with_foo(Foo.X(bar), 3), 5)
}

OUTPUT:

---
package main

func main() {
	bar := make_Bar_A(2)

	assertEq[int](with_foo(make_Foo_X(bar), 3), 5)
}
